### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by demoskalifi** [fundwotsai2001/AP-adapter#2]
Can I use this in my commercial music app?
I'm asking because I've seen you use AudioLDM2, and it's weights is licensed under Attribution-NonCommercial-ShareAlike 4.0 International

**Comment by fundwotsai2001** [comment]
Sorry, I am afraid that if AudioLDM2 is using a noncommercial license, you should not use this project in your commercial app.
We will change our license to the same as AudioLDM2.

**Comment by demoskalifi** [comment]
First off, I gotta say, the tech you introduced is amazing! It got me wondering if we could replicate these editorial capabilities using a fully open-source model like "stable-audio-open." I noticed it already has a comfy-UI node and lots of fine-tunes floating around the internet.

Also, just a friendly suggestion: maybe you could use a dual licensing approach? Like, AudioLDM could be under Attribution-NonCommercial-ShareAlike 4.0 International, and the rest of the code under the MIT license. That way, others can build on it more easily.

Thanks for the awesome work and your quick reply

**Comment by fundwotsai2001** [comment]
Thanks for your suggestion, I will discuss this with my advisor.

**Comment by fundwotsai2001** [comment]
Sorry for the late reply, now our repo is under two licenses, CC-BY-NC-SA-4.0 License, and Apache-2.0 License. Thanks for your suggestion.
